[package]
name    = "examples3d"
version = "0.1.0"
authors = [ "Sébastien Crozet <developer@crozet.re>" ]
edition = "2018"

[features]
parallel = [ "nphysics_testbed3d/parallel"]

[dependencies]
num-traits = "0.2"
Inflector  = "0.11"
# nalgebra   = "0.21"
nalgebra = { version = "0.21", features = [ "serde-serialize" ] }

ncollide3d = "0.23"
kiss3d     = "0.24"
nphysics3d = "0.16"
nphysics_testbed3d = { version = "0.10", features = [ "fluids" ] }
serde = "1.0.115"
serde_json = "1.0.57"
uuid = { version = "0.8", features = ["serde", "v4"] }

[dependencies.salva3d]
path = "../build/salva3d"
features = [ "nphysics", "sampling" ]

[target.wasm32-unknown-unknown.dependencies]
stdweb = "0.4"

[target.wasm32-unknown-emscripten.dependencies]
stdweb = "0.4"

[target.asmjs-unknown-emscripten.dependencies]
stdweb = "0.4"

[[bin]]
name = "all_examples3"
path = "./all_examples3.rs"

[[bin]]
name = "fluids3"
path = "basic3.rs"
